name: Documentation

on:
  push:
    branches:
      - 'main'
    tags: '*'
    paths-ignore:
      - '.zenodo.json'
      - '.github/workflows/benchmark.yml'
      - '.github/workflows/ci.yml'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
      - 'benchmark/**'
      - 'utils/**'
  pull_request:
    paths-ignore:
      - '.zenodo.json'
      - '.github/workflows/benchmark.yml'
      - '.github/workflows/ci.yml'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
      - 'benchmark/**'
      - 'utils/**'
  workflow_dispatch:

# Cancel redundant CI tests automatically
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
          show-versioninfo: true
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""
      - name: Run Python benchmarks
        run: |
          # Install pybs and run benchmark
          git clone https://github.com/henriksu/pybs.git python_pybs
          cd python_pybs
          git checkout 832f037cc342f5c3808c8f50a869b7b9ffb9b170
          # We need to fix pybs due to CI failures, see
          # https://github.com/ranocha/BSeries.jl/pull/32
          ls -R
          rm pybs/__init__.py
          pip install -e .
          cd ..
          pip list
          python --version
          python docs/src/benchmark_python_pybs.py
          # Install BSeries & noedpy and run benchmark
          git clone https://github.com/ketch/BSeries.git python_bseries
          cd python_bseries
          pip install .
          pip install nodepy
          cd ..
          pip list
          python --version
          python docs/src/benchmark_python_bseries.py
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        env:
          PYTHON: ""
      - name: Install Python dependencies
        shell: julia --project=. --color=yes {0}
        run: |
          using Pkg
          Pkg.add("PyCall")
          using PyCall.Conda
          Conda.pip_interop(true)
          # install known versions of other packages working with B-series
          Conda.pip("install",
            "git+https://github.com/ketch/BSeries.git@f0bfd9c74f155c9e4a7bc748255c5f6cc2948e9b")
          Conda.pip("install",
            "git+https://github.com/henriksu/pybs.git@832f037cc342f5c3808c8f50a869b7b9ffb9b170")
          # nodepy is used for examples using BSeries in Python
          Conda.pip("install", "nodepy")
          Conda.list()
          # Next, we need to fix pybs due to CI failures, see
          # https://github.com/ranocha/BSeries.jl/pull/32
          using PyCall
          @show PyCall.pyversion
          @show PyCall.libpython
          @show PyCall.pyprogramname
          @show PyCall.Conda.PYTHONDIR
          @show PyCall.Conda.LIBDIR
          # PyCall.python_cmd(`-v -m pybs`) |> run
          rm(joinpath(PyCall.Conda.LIBDIR, "python3.9", "site-packages", "pybs", "__init__.py"),
             force=true)
          PyCall.python_cmd(`-c "import pybs"`) |> run |> println
          PyCall.python_cmd(`-c "import pybs; print(pybs.__path__)"`) |> run
          run(`ls -R $(joinpath(PyCall.Conda.LIBDIR, "python3.9", "site-packages", "pybs"))`)
          PyCall.python_cmd(`docs/src/benchmark_python_pybs.py`) |> run
      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
          GKSwstype: "100" # https://discourse.julialang.org/t/generation-of-documentation-fails-qt-qpa-xcb-could-not-connect-to-display/60988
          PYTHON: ""
        run: julia --project=docs --color=yes docs/make.jl
